### PR TITLE
Fix return values types

### LINKED ISSUE #513: admin: function call fails when the function arguments is an empty table
cartridge-cli version 2.7.1
cartridge-cli-extensions 1.1.0

I created an admin function without arguments
```
admin_tasks.cleanup = {
    -- описываем новую функцию
    usage = 'Clean old products from cache',
    args = {},
    call = function(opts)
       ...
    end
}
```

When calling this function I get:
```
Failed to parse function call args: Failed to get "cleanup" arguments spec: 
Failed to convert to map: Isn't a map: []interface {}{}. 
Please update cartridge-cli-extensions module or file an issue 
https://github.com/tarantool/cartridge-cli-extensions/issues/new
```

### PR DESCRIPTION
**Pull request by dokshina**
All returned maps have `{__serialize = 'map'}` set.
Cartridge CLI calls ExecTyped using connectors. 
Such calls expects map values, but Lua empty tables are serialized as arrays by default.

Closes https://github.com/tarantool/cartridge-cli/issues/513

### CODE REVIEW

**Review by olegrok — APPROVED** [review]

File: cartridge-cli-extensions/admin.lua [hunk 1]
```diff
@@ -130,7 +130,7 @@ local function admin_help(func_name)
 
     return {
         usage = registry[func_name].usage,
-        args = registry[func_name].args,
+        args = setmetatable(registry[func_name].args or {}, {__serialize = 'map'}),
```
Comment (olegrok) [inline cartridge-cli-extensions/admin.lua:135]: Is it possible `registry[func_name].args` to be `box.NULL`?

**Review by olegrok — APPROVED** [review]
